#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — deploy do AVIA: backend no Render, frontend no Vercel.
#
# Rode este script a partir da raiz do repo (assistente_IA/). Ele te leva pelo
# dashboard do Render e do Vercel; você clica, ele guarda as URLs e monta o
# frontend/.env. Pode parar com Ctrl-C a qualquer momento e rodar de novo —
# ele lembra o que já foi preenchido.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="frontend/.env"

banner "Deploy do AVIA — Render + Vercel"

# ── Stage 1: backend no Render ─────────────────────────────────────────────
stage "Render — publicar o backend"
say "O repo já tem um render.yaml (Blueprint) na raiz — o Render lê ele sozinho"
say "e já sabe como buildar (uv sync) e iniciar (fastapi run) o backend."
open_url "https://dashboard.render.com/"
step "Se ainda não tiver conta, crie uma — entrar com GitHub é o mais rápido"
step "  (já autoriza o acesso ao repositório de uma vez)."
step "Clique em 'New +' → 'Blueprint'."
step "Conecte a conta do GitHub se pedir, e selecione o repositório"
step "  joyceximenes/assistente_IA."
step "O Render vai detectar o render.yaml e mostrar o serviço 'avia-backend'."
step "  Clique em 'Apply' (ou 'Create New Resources')."
note "Nesse passo ele vai pedir os valores de OCR_SPACE_API_KEY e"
note "HUGGINGFACE_API_TOKEN (estão marcados sync: false no render.yaml, por"
note "isso não vêm do repositório). Abra backend/.env no seu editor e copie"
note "os dois valores de lá para o formulário do Render."
pause "Colou as duas chaves e clicou em Deploy? Enter para continuar."
say "O primeiro build demora alguns minutos (instala o uv, sincroniza as"
say "dependências, sobe o servidor). Acompanhe em 'Logs' até aparecer algo"
say "como 'Application startup complete' ou o serviço ficar 'Live'."
pause "Build terminou e o serviço está 'Live'? Enter para continuar."
step "Copie a URL pública do serviço, no topo da página (formato"
step "  https://avia-backend-XXXX.onrender.com)."
ask BACKEND_URL "Cole a URL pública do backend:"
BACKEND_URL="${BACKEND_URL%/}" # remove barra final, se tiver
write_env VITE_API_BASE_URL "$BACKEND_URL"

# ── Stage 2: checar se o backend está de pé ─────────────────────────────────
stage "Conferir o backend no ar"
say "Antes de mexer no frontend, vale confirmar que o backend responde."
open_url "${BACKEND_URL}/health"
step "Essa URL deve devolver {\"status\":\"ok\"}. Se der erro ou ficar girando,"
step "  volte no Render → Logs e veja o que travou antes de seguir."
confirm "A rota /health respondeu {\"status\":\"ok\"}?" || warn "resolva isso no Render antes de continuar — os próximos passos dependem do backend estar de pé"

# ── Stage 3: frontend no Vercel ─────────────────────────────────────────────
stage "Vercel — publicar o frontend"
say "O frontend é estático (Vite) — o Vercel detecta o framework sozinho."
open_url "https://vercel.com/new"
step "Entre com sua conta do GitHub."
step "Encontre 'assistente_IA' na lista de repositórios (autorize o acesso"
step "  se ele pedir) e clique em 'Import'."
step "Em 'Root Directory', clique em 'Edit' e selecione 'frontend'."
step "Confira que 'Framework Preset' ficou como 'Vite' (é automático depois"
step "  de trocar o Root Directory)."
step "Em 'Environment Variables', adicione:"
note "  Name:  VITE_API_BASE_URL"
note "  Value: $BACKEND_URL"
step "Clique em 'Deploy' e aguarde (bem mais rápido que o backend, é estático)."
step "Quando terminar, copie a URL pública gerada (formato"
step "  https://assistente-ia-xxxx.vercel.app)."
ask FRONTEND_URL "Cole a URL pública do frontend:"
FRONTEND_URL="${FRONTEND_URL%/}" # remove barra final, se tiver

# ── Stage 4: liberar o CORS do backend para o domínio do Vercel ────────────
stage "Render — liberar o CORS para o domínio do Vercel"
say "Sem isso, o navegador bloqueia as chamadas do frontend pro backend."
open_url "https://dashboard.render.com/"
step "Abra o serviço 'avia-backend' → aba 'Environment'."
step "Edite a variável CORS_ALLOWED_ORIGINS. Novo valor (cole exatamente,"
step "  sem espaços, sem barra no final da URL do Vercel):"
note "  http://localhost:5173,http://127.0.0.1:5173,$FRONTEND_URL"
step "Salve. O Render reinicia o serviço sozinho — não precisa de redeploy manual."
pause "Salvou a variável e o serviço reiniciou (status 'Live' de novo)? Enter para continuar."

# ── Stage 5: verificação ponta a ponta ──────────────────────────────────────
stage "Verificação ponta a ponta"
say "Hora de testar o fluxo completo no site publicado."
open_url "$FRONTEND_URL"
step "Tire uma foto de um texto ou objeto e confirme que a resposta chega"
step "  (sem travar, sem erro)."
step "Abra o DevTools (F12) → aba Console — não deve aparecer erro de CORS."
step "No celular, tente instalar o PWA (é o motivo de todo esse deploy —"
step "  os testes do TESTES.xlsx que travavam com 'Requer HTTPS')."
note "Se aparecer erro de CORS no console: confira se a URL do Vercel no"
note "CORS_ALLOWED_ORIGINS do Render está EXATAMENTE igual (https, sem"
note "barra no final) à URL que abriu de verdade no navegador."
confirm "Fluxo completo funcionando (foto → resposta, sem erro de CORS)?" || warn "anote o erro exato do console — é o próximo passo a investigar, não repita o wizard sem isso"
# ──────────────────────────────────────────────────────────────────────────

finish
